### ISSUE TITLE
Compiling a script on Linux fails

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#655]
# Symptoms
When compiling an empty `CONTEXT` in RAP3, I get the following Slim Application Error:
![image](https://cloud.githubusercontent.com/assets/275768/24905576/bcfedd96-1eb4-11e7-99df-8a557c767d65.png)
Apparently, the directory in which RAP3 writes the new script is not being created because of an authorization failure.
# Context
This error occurs on the Azure-server, http://52.174.4.78/RAP3.
Compilation of RAP3 files was successful.
The Slim Application Error reads as follows:
~~~~~~
#0 [internal function]: CompileToNewVersion('Script_14919073...', '123456')
#1 /opt/bitnami/apache2/htdocs/RAP3/extensions/ExecEngine/ExecEngine.php(157): call_user_func_array('CompileToNewVer...', Array)
#2 /opt/bitnami/apache2/htdocs/RAP3/extensions/ExecEngine/ExecEngine.php(105): Ampersand\Extension\ExecEngine\ExecEngine::fixViolations(Array)
#3 [internal function]: Ampersand\Extension\ExecEngine\ExecEngine::run()
#4 /opt/bitnami/apache2/htdocs/RAP3/src/Ampersand/Hooks.php(40): call_user_func_array('\\Ampersand\\Exte...', Array)
#5 /opt/bitnami/apache2/htdocs/RAP3/src/Ampersand/Database/Database.php(666): Ampersand\Hooks::callHooks('preDatabaseClos...', Array)
#6 /opt/bitnami/apache2/htdocs/RAP3/src/Ampersand/Core/Atom.php(607): Ampersand\Database\Database->closeTransaction('Script updated', NULL, Object(Ampersand\Core\Atom))
#7 /opt/bitnami/apache2/htdocs/RAP3/api/v1/resources.php(118): Ampersand\Core\Atom->patch(Array, Array)
#8 [internal function]: {closure}('Script', 'Script_14919073...', Array)
#9 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#10 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#11 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#12 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#13 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Middleware/ContentTypes.php(81): Slim\Middleware\MethodOverride->call()
#14 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\ContentTypes->call()
#15 /opt/bitnami/apache2/htdocs/RAP3/lib/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#16 /opt/bitnami/apache2/htdocs/RAP3/api/v1/index.php(75): Slim\Slim->run()
#17 {main}
~~~~~~

**Comment by Michiel-s** [comment]
Error message provides the reasons: 'No script content specified'. You didn't specify any content (or didn't save the script) before compiling.
