### ISSUE TITLE
Error failed to parse time string when no value provided

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#904]
![image](https://user-images.githubusercontent.com/7961582/52334208-705c3080-29ff-11e9-9130-baf83b5b59dc.png)

```
Type: Exception
Message: DateTime::__construct(): Failed to parse time string (NaN-NaN-NaN) at position 0 (N): The timezone could not be found in the database
File: C:\dev\xampp\htdocs\project\src\Ampersand\Core\Atom.php
Line: 95
Trace
#0 C:\dev\xampp\htdocs\project\src\Ampersand\Core\Atom.php(95): DateTime->__construct('NaN-NaN-NaN')
#1 C:\dev\xampp\htdocs\project\src\Ampersand\Core\Atom.php(48): Ampersand\Core\Atom->setId('NaN-NaN-NaN')
#2 C:\dev\xampp\htdocs\project\src\Ampersand\Interfacing\InterfaceExprObject.php(794): Ampersand\Core\Atom->__construct('NaN-NaN-NaN', Object(Ampersand\Core\Concept))
#3 C:\dev\xampp\htdocs\project\src\Ampersand\Interfacing\InterfaceExprObject.php(766): Ampersand\Interfacing\InterfaceExprObject->add(Object(Ampersand\Interfacing\Resource), 'NaN-NaN-NaN')
#4 C:\dev\xampp\htdocs\project\src\Ampersand\Interfacing\ResourceList.php(214): Ampersand\Interfacing\InterfaceExprObject->set(Object(Ampersand\Interfacing\Resource), 'NaN-NaN-NaN')
#5 C:\dev\xampp\htdocs\project\src\Ampersand\Interfacing\Resource.php(291): Ampersand\Interfacing\ResourceList->set('NaN-NaN-NaN')
#6 C:\dev\xampp\htdocs\project\public\api\v1\resources.php(132): Ampersand\Interfacing\Resource->patch(Array)
#7 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 C:\dev\xampp\htdocs\project\public\api\v1\index.php(186): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#13 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#14 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 C:\dev\xampp\htdocs\project\public\api\v1\index.php(154): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#20 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#22 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 C:\dev\xampp\htdocs\project\public\api\v1\index.php(205): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#25 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#26 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#27 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#28 C:\dev\xampp\htdocs\project\public\api\v1\index.php(263): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#29 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#30 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#32 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#33 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#34 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#35 C:\dev\xampp\htdocs\project\lib\slim\slim\Slim\App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#36 C:\dev\xampp\htdocs\project\public\api\v1\index.php(264): Slim\App->run()
#37 {main}
```

**Comment by stefjoosten** [comment]
@Michiel-s,
This issue still lacks an analysis. Have you made the analysis yet? Anything someone else can do?
